#
# Module manifest for module Activate-VirtualEnv
#
# Generated by: Paulo Romano (pauloromanocarvalho@gmail.com)
#
# Generated on: 17/12/2015
#

@{

ModuleToProcess = 'Activate-VirtualEnv.psm1'
ModuleVersion = '0.1'
GUID = 'd57664f1-89bb-4a23-9d79-423fe174ba01'
Author = 'Paulo Romano'
CompanyName = 'Unknown'
Copyright = '(c) 2015 Paulo Romano. All rights reserved.'
Description = ''
PowerShellVersion = ''
PowerShellHostName = ''
PowerShellHostVersion = ''
DotNetFrameworkVersion = ''
CLRVersion = ''
ProcessorArchitecture = ''
RequiredModules = @()
RequiredAssemblies = @()
ScriptsToProcess = @()
TypesToProcess = @()
FormatsToProcess = @()
NestedModules = @()
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
ModuleList = @()
FileList = @()
PrivateData = ''

}

